namespace: mysql

image:
  repository: mysql
  tag: "8.0"

replicas: 3

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

pvc:
  storage: 2Gi

affinity:
  nodeAffinity:
    key: app
    values: ["mysql"]
  podAntiAffinity: true
tolerations:
  - key: "app"
    operator: "Equal"
    value: "mysql"
    effect: "NoSchedule"

secrets:
  - name: MYSQL_ROOT_PASSWORD
    value: rootpass
  - name: MYSQL_USER
    value: appuser
  - name: MYSQL_PASSWORD
    value: apppass
