apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-auth
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
