apiVersion: v2
name: todoapp
description: Todo application with MySQL subchart
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mysql # <-- цей рядок має існувати буквально
    version: 0.1.0
    repository: "file://charts/mysql"
