apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
