apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-env
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range .Values.secrets }}
  {{ .name }}: "{{ .value }}"
{{- end }}
