apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "todoapp" .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "todoapp.name" . | default "todoapp" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
